
" Pathogen (tpope/vim-pathogen)
call pathogen#infect()

syntax on
set background=dark
colorscheme molokai

set history=500
filetype plugin on
filetype indent on
set autoread
set wildmenu
set wildignore=*.o,*~,*.pyc,*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
set ruler
set cmdheight=2
set hid
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw
set magic
set showmatch
set mat=2
set noerrorbells
set novisualbell
set t_vb=
set tm=500
set foldcolumn=1
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set tw=500
set ai
set si
set wrap
set number
set nocompatible
set linebreak
set mouse=a
set foldmethod=marker
set foldlevelstart=1
set encoding=utf-8
set fileencodings=utf-8
set tags=./tags,./TAGS,tags,TAGS
set autoindent
set smartindent
set cindent
set shiftwidth=4
set wildignore=*.pyc

set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c
function! HasPaste()
  if &paste
    return 'PASTE MODE  '
  endif
    return ''
endfunction

let g:user_zen_mode='a'
let g:go_fmt_command="goimports"
let g:syntastic_auto_loc_list=1
let g:syntastic_go_checkers=['go', 'golint', 'errcheck']

