" pathogen
call pathogen#infect()
syntax on
filetype plugin indent on
colorscheme railscasts


set nocompatible
set linebreak
set number
set mouse=a
set foldmethod=marker
set foldlevelstart=1
set encoding=utf-8
set fileencodings=utf-8
set tags=./tags,./TAGS,tags,TAGS
set autoindent
set smartindent
set cindent
set expandtab
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=4
set wildignore=*.pyc
set ignorecase
set smartcase
set hlsearch
set incsearch
set shiftround
set history=1000
set undolevels=1000
set noswapfile
set nobackup
set linespace=3
set hidden

if has("cscope")
  set csto=0
  set cst
  set nocsverb
  set csverb
endif

" remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

