
" Pathogen (tpope/vim-pathogen)
call pathogen#infect()

syntax on
filetype plugin indent on
colorscheme molokai

set number

set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c
function! HasPaste()
  if &paste
    return 'PASTE MODE  '
  endif
    return ''
endfunction

let g:user_zen_mode='a'
let g:go_fmt_command="goimports"
let g:syntastic_auto_loc_list=1
let g:syntastic_go_checkers=['go', 'golint', 'errcheck']

