export ZSH=$HOME/.oh-my-zsh
export ZSH_PLUGINS=$HOME/.zsh-plugins
ZSH_THEME="robbyrussell"

plugins=(git nvm brew docker)

source $ZSH/oh-my-zsh.sh

export LANGUAGE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=vim

# go
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/go/bin

# nvm
export NVM_DIR=$HOME/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

